<?php

use Drupal\Core\Render\Element;

/**
 * Implements theme_hook().
 *
 * Add the form template with preprocess to override.
 * Form is used on the top of the main guestbook page.
 * Add hook for using custom template for rendering FeedbackEntity.
 */
function yuraul_theme() {
  return [
    'feedback_entity_add2_form' =>
      [
        'render element' => 'form',
        'file' => 'yuraul.theme.inc',
      ],
    'feedback_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements theme_preprocess_hook().
 *
 * Prepares variables for sponsor templates.
 *
 * @param $variables
 *   The variables array (modify in place).
 */
function template_preprocess_feedback_entity(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
