<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function yuraul_form_feedback_entity_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#theme'] = ['myform'];
}

function yuraul_theme() {
  $a = 1;
  $themes['myform'] = [
    'render element' => 'form',
    ];

   return $themes;
//  return [
//    'node__feedback_post__teaser' => [
//      'template' => 'node--feedback-post--teaser',
//      'base hook' => 'node',
//    ],
//    'form__feedback_entity_add_form' => [
//      'template' => 'form--feedback-entity-add-form',
//      'base hook' => 'form',
//    ],
//  ];
}

///**
// * Implements hook_theme_suggestions_alter
// */
//function yuraul_theme_suggestions_alter(array &$suggestions, array $variables)
//{
//
//  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
//    $original_theme_hook = $variables['theme_hook_original'];
//
//    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
//  }
//
//  return $suggestions;
//
//}


///**
// * Implements hook_form_FORM_ID_alter().
// * Form ID: add_feedback
// */
//function yuraul_form_add_feedback_alter(&$form, FormStateInterface  &$form_state) {
//  // If buildForm() method received $postID we know form was invoked to
//  // edit post, so fill inputs with a values of appropriate post and
//  // change the name of save button and add delete submit button.
//  $post = $form_state->getBuildInfo()['args'][0][0] ?? FALSE;
//  if ($post) {
//    $form['fieldset']['#title'] = t("Edit post# @postID", ['@postID' => $post->post_id]);
//    $form['fieldset']['upper']['left']['username']['#default_value'] = $post->username;
//    $form['fieldset']['upper']['left']['email']['#default_value'] = $post->email;
//    $form['fieldset']['upper']['left']['phone']['#default_value'] = "+{$post->phone}";
//    $form['fieldset']['upper']['right']['avatar']['#default_value'] = [$post->avatar];
//    $form['fieldset']['upper']['right']['picture']['#default_value'] = [$post->picture];
//    $form['fieldset']['message']['#default_value'] = $post->message;
//    $form['fieldset']['actions']['save']['#name'] = 'update';
//    $form['fieldset']['actions']['save']['#value'] = t('Update');
//
//    $form['fieldset']['actions']['delete'] = [
//      '#type' => 'submit',
//      '#name' => 'delete',
//      '#button_type' => 'primary',
//      '#value' => 'Delete',
//      '#ajax' => [
//        'callback' => '::ajaxSubmit',
//        'event' => 'click',
//        'progress' => [
//          'type' => 'throbber',
//        ],
//      ],
//    ];
//  }
//}
